//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSetupAutomationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAP_FieldTypes
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> UseDataSource { get; set; }
        public Nullable<bool> UseOptions { get; set; }
    }
}
