//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSetupAutomationPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IAP_Fields
    {
        public long Id { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string FieldLabel { get; set; }
        public Nullable<int> FieldLenght { get; set; }
        public string FieldDataSource { get; set; }
        public string FieldOptions { get; set; }
    }
}
