//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItemSetupAutomationPlatform.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItemAutomationPlatformEntities : DbContext
    {
        public ItemAutomationPlatformEntities()
            : base("name=ItemAutomationPlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IAP_Fields> IAP_Fields { get; set; }
        public virtual DbSet<IAP_FieldTypes> IAP_FieldTypes { get; set; }
    }
}
